name: Test & Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
#    services:
#      postgres:
#        image: postgres:15
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: changeme
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#      kafka:
#        image: bitnami/kafka:3.4
#        env:
#          ALLOW_PLAINTEXT_LISTENER: yes
#          KAFKA_CFG_LISTENERS: PLAINTEXT://:9094,CONTROLLER://:9093
#          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094
#          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
#        options: >-
#          --health-cmd "kafka-broker-api-versions.sh --version"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run make deps
        run: make deps

      - name: Check dep changes
        run: if [ -n "$(git status --porcelain)" ]; then git status --porcelain && exit 1; fi

      - name: Run make lint
        run: make lint

      - name: Run tests
#        env:
#          DB_TEST_URL: postgres://postgres:changeme@postgres:5432/%s?sslmode=disable
#          KAFKA_TEST_URL: kafka:9094
        run: make test-cov-docker

      - name: Run build
        run: make build